# Generated by Django 5.2.16 on 2026-07-14 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=120, verbose_name='Краткое наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующее')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.division', verbose_name='Вышестоящее подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'подразделения',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OperationalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_areas', to='organizations.division', verbose_name='Подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_areas', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'оперативная область',
                'verbose_name_plural': 'оперативные области',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_operational', models.BooleanField(default=False, verbose_name='Оперативная должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.CharField(max_length=64, verbose_name='Табельный номер')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('employment_start', models.DateField(default=django.utils.timezone.localdate, verbose_name='Начало работы')),
                ('employment_end', models.DateField(blank=True, null=True, verbose_name='Окончание работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий сотрудник')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.division', verbose_name='Подразделение')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Персональная учётная запись')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ('last_name', 'first_name', 'middle_name'),
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('operational_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsibility_scopes', to='organizations.operationalarea', verbose_name='Оперативная область')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibility_scopes', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'область ответственности',
                'verbose_name_plural': 'области ответственности',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующее назначение')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.employee', verbose_name='Сотрудник')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organizations.role', verbose_name='Роль')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.responsibilityscope', verbose_name='Область ответственности')),
            ],
            options={
                'verbose_name': 'назначение роли',
                'verbose_name_plural': 'назначения ролей',
                'ordering': ('employee__last_name', 'role__name', 'valid_from'),
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(verbose_name='Действует по')),
                ('reason', models.CharField(max_length=500, verbose_name='Основание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующее замещение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('replaced_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_as_replaced', to='organizations.employee', verbose_name='Замещаемый сотрудник')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='organizations.responsibilityscope', verbose_name='Ограничение области ответственности')),
                ('substitute_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_as_substitute', to='organizations.employee', verbose_name='Замещающий сотрудник')),
            ],
            options={
                'verbose_name': 'временное замещение',
                'verbose_name_plural': 'временные замещения',
                'ordering': ('-valid_from', 'replaced_employee__last_name'),
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующее')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workplaces', to='organizations.division', verbose_name='Подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workplaces', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'рабочее место',
                'verbose_name_plural': 'рабочие места',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='operationalarea',
            name='workplaces',
            field=models.ManyToManyField(blank=True, related_name='operational_areas', to='organizations.workplace', verbose_name='Рабочие места'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.workplace', verbose_name='Основное рабочее место'),
        ),
        migrations.CreateModel(
            name='AuthenticationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Успешный вход'), ('LOGIN_FAILURE', 'Неуспешный вход'), ('LOGOUT', 'Выход')], max_length=32, verbose_name='Событие')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('username_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='Ключ сессии')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authentication_events', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authentication_events', to='organizations.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'событие аутентификации',
                'verbose_name_plural': 'события аутентификации',
                'ordering': ('-occurred_at', '-pk'),
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='organizatio_event_t_835441_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_division_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_position_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='responsibilityscope',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_scope_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='role_assignment_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'role', 'scope', 'valid_from'), name='uniq_scoped_role_assignment_start'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope__isnull', True)), fields=('employee', 'role', 'valid_from'), name='uniq_global_role_assignment_start'),
        ),
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='substitution_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.UniqueConstraint(fields=('replaced_employee', 'substitute_employee', 'scope', 'valid_from'), name='uniq_substitution_start'),
        ),
        migrations.AddConstraint(
            model_name='workplace',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_workplace_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='operationalarea',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_area_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'personnel_number'), name='uniq_employee_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_end__isnull', True), ('employment_end__gte', models.F('employment_start')), _connector='OR'), name='employee_valid_employment_window'),
        ),
    ]
