# Generated by Django 5.2.16 on 2026-07-15 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial_organizational_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('DARK', 'Тёмная'), ('LIGHT', 'Светлая'), ('SYSTEM', 'Как в системе')], default='DARK', max_length=16, verbose_name='Цветовая схема')),
                ('density', models.CharField(choices=[('COMFORTABLE', 'Комфортная'), ('COMPACT', 'Компактная')], default='COMFORTABLE', max_length=16, verbose_name='Плотность интерфейса')),
                ('font_scale', models.CharField(choices=[('SMALL', 'Мелкий'), ('NORMAL', 'Обычный'), ('LARGE', 'Крупный')], default='NORMAL', max_length=16, verbose_name='Размер текста')),
                ('content_width', models.CharField(choices=[('STANDARD', 'Стандартная'), ('WIDE', 'Широкая')], default='STANDARD', max_length=16, verbose_name='Ширина рабочей области')),
                ('show_technical_details', models.BooleanField(default=False, verbose_name='Показывать технические реквизиты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interface_preference', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
            options={
                'verbose_name': 'настройки интерфейса',
                'verbose_name_plural': 'настройки интерфейса',
            },
        ),
    ]
