# Generated by Django 5.2.16 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_operational_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_density",
            field=models.CharField(
                choices=[
                    ("COMPACT", "Компактная"),
                    ("NORMAL", "Обычная"),
                    ("RELAXED", "Увеличенная"),
                ],
                default="NORMAL",
                max_length=16,
                verbose_name="Плотность строк журнала",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_font_family",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "Системный"),
                    ("ARIAL", "Arial"),
                    ("PT_SANS", "PT Sans"),
                    ("TIMES", "Times New Roman"),
                ],
                default="SYSTEM",
                max_length=16,
                verbose_name="Шрифт записей журнала",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_font_size",
            field=models.CharField(
                choices=[
                    ("SMALL", "Мелкий"),
                    ("NORMAL", "Обычный"),
                    ("LARGE", "Крупный"),
                    ("EXTRA_LARGE", "Очень крупный"),
                ],
                default="NORMAL",
                max_length=16,
                verbose_name="Размер текста записей",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_heading_mode",
            field=models.CharField(
                choices=[
                    ("COMPACT", "Компактная"),
                    ("FULL", "Полная"),
                    ("HIDDEN", "Скрытая"),
                ],
                default="COMPACT",
                max_length=16,
                verbose_name="Режим шапки журнала",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_show_authors",
            field=models.BooleanField(default=True, verbose_name="Показывать авторов записей"),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_show_links",
            field=models.BooleanField(default=True, verbose_name="Показывать связи записей"),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_width",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Стандартная"),
                    ("WIDE", "Широкая"),
                    ("FULL", "На всю доступную ширину"),
                ],
                default="WIDE",
                max_length=16,
                verbose_name="Ширина журнала",
            ),
        ),
    ]
