# Generated by Django 5.2.16 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_journal_presentation_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_date_font_size",
            field=models.CharField(
                choices=[
                    ("SMALL", "Мелкий"),
                    ("NORMAL", "Обычный"),
                    ("LARGE", "Крупный"),
                    ("EXTRA_LARGE", "Очень крупный"),
                ],
                default="NORMAL",
                max_length=16,
                verbose_name="Размер заголовков дат",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_table_header_font_size",
            field=models.CharField(
                choices=[
                    ("SMALL", "Мелкий"),
                    ("NORMAL", "Обычный"),
                    ("LARGE", "Крупный"),
                    ("EXTRA_LARGE", "Очень крупный"),
                ],
                default="NORMAL",
                max_length=16,
                verbose_name="Размер шапки таблицы",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_time_font_size",
            field=models.CharField(
                choices=[
                    ("SMALL", "Мелкий"),
                    ("NORMAL", "Обычный"),
                    ("LARGE", "Крупный"),
                    ("EXTRA_LARGE", "Очень крупный"),
                ],
                default="NORMAL",
                max_length=16,
                verbose_name="Размер времени записи",
            ),
        ),
        migrations.AddField(
            model_name="interfacepreference",
            name="journal_title_font_size",
            field=models.CharField(
                choices=[
                    ("SMALL", "Мелкий"),
                    ("NORMAL", "Обычный"),
                    ("LARGE", "Крупный"),
                    ("EXTRA_LARGE", "Очень крупный"),
                ],
                default="NORMAL",
                max_length=16,
                verbose_name="Размер заголовка журнала",
            ),
        ),
    ]
