# Generated by Django 5.2.16 on 2026-07-17 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("normatives", "0001_normative_registry"),
        ("organizations", "0003_operational_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkplaceDocumentList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=96, verbose_name="Код перечня")),
                ("title", models.CharField(max_length=500, verbose_name="Наименование перечня")),
                ("is_active", models.BooleanField(default=True, verbose_name="Используется")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workplace_document_lists",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_lists",
                        to="organizations.workplace",
                        verbose_name="Рабочее место",
                    ),
                ),
            ],
            options={
                "verbose_name": "перечень документации рабочего места",
                "verbose_name_plural": "перечни документации рабочих мест",
                "ordering": ("organization__name", "workplace__name", "title"),
            },
        ),
        migrations.CreateModel(
            name="WorkplaceDocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField(verbose_name="Номер редакции")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Черновик"), ("APPROVED", "Утверждена")],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                ("effective_until", models.DateField(blank=True, null=True, verbose_name="Действует по")),
                (
                    "review_period_months",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Периодичность пересмотра, месяцев"
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="Следующий пересмотр",
                    ),
                ),
                ("change_summary", models.TextField(blank=True, verbose_name="Описание редакции")),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Утверждена"),
                ),
                (
                    "digest",
                    models.CharField(
                        blank=True, editable=False, max_length=64, verbose_name="SHA-256 редакции"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_workplace_document_revisions",
                        to="organizations.employee",
                        verbose_name="Утвердил",
                    ),
                ),
                (
                    "document_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="workplace_docs.workplacedocumentlist",
                        verbose_name="Перечень",
                    ),
                ),
            ],
            options={
                "verbose_name": "редакция перечня документации",
                "verbose_name_plural": "редакции перечней документации",
                "ordering": ("document_list", "-revision_number"),
            },
        ),
        migrations.CreateModel(
            name="WorkplaceDocumentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=96, verbose_name="Код позиции")),
                ("title", models.CharField(max_length=500, verbose_name="Наименование документации")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("TYPICAL", "Типовая позиция"), ("LOCAL", "Локальная позиция")],
                        max_length=16,
                        verbose_name="Происхождение",
                    ),
                ),
                (
                    "requirement_kind",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Обязательная"),
                            ("CONDITIONAL", "Обязательная при применимости"),
                            ("REFERENCE", "Справочная"),
                        ],
                        default="MANDATORY",
                        max_length=16,
                        verbose_name="Обязательность",
                    ),
                ),
                ("applicability_text", models.TextField(blank=True, verbose_name="Применимость")),
                (
                    "storage_form",
                    models.CharField(
                        choices=[
                            ("PAPER", "Бумажная"),
                            ("ELECTRONIC", "Электронная"),
                            ("MIXED", "Смешанная"),
                        ],
                        max_length=16,
                        verbose_name="Форма хранения",
                    ),
                ),
                (
                    "normative_clause",
                    models.CharField(blank=True, max_length=128, verbose_name="Пункт нормативного документа"),
                ),
                ("basis_text", models.CharField(blank=True, max_length=1000, verbose_name="Основание")),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="Порядок отображения")),
                (
                    "normative_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workplace_document_entries",
                        to="normatives.normativedocument",
                        verbose_name="Нормативный документ",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="workplace_docs.workplacedocumentrevision",
                        verbose_name="Редакция перечня",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция перечня документации",
                "verbose_name_plural": "позиции перечня документации",
                "ordering": ("revision", "display_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="WorkplaceDocumentAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("REVISION_APPROVED", "Редакция утверждена")],
                        max_length=32,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Время"
                    ),
                ),
                ("snapshot", models.JSONField(default=dict, editable=False, verbose_name="Снимок")),
                ("digest", models.CharField(editable=False, max_length=64, verbose_name="SHA-256 события")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workplace_document_audit_events",
                        to="organizations.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "document_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="workplace_docs.workplacedocumentlist",
                        verbose_name="Перечень",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="workplace_docs.workplacedocumentrevision",
                        verbose_name="Редакция",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие перечня документации",
                "verbose_name_plural": "события перечней документации",
                "ordering": ("-event_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="workplacedocumentlist",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_workplace_document_list_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="workplacedocumentrevision",
            constraint=models.UniqueConstraint(
                fields=("document_list", "revision_number"), name="uniq_workplace_document_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="workplacedocumentrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="workplace_document_revision_valid_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="workplacedocumentrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True),
                        ("approved_by__isnull", True),
                        ("digest", ""),
                        ("next_review_date__isnull", True),
                        ("status", "DRAFT"),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("approved_by__isnull", False),
                        ("next_review_date__isnull", False),
                        ("status", "APPROVED"),
                        models.Q(("digest", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="workplace_document_revision_approval_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="workplacedocumententry",
            constraint=models.UniqueConstraint(
                fields=("revision", "code"), name="uniq_workplace_document_entry_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="workplacedocumentauditevent",
            constraint=models.UniqueConstraint(
                fields=("revision", "event_type"), name="uniq_workplace_document_revision_event"
            ),
        ),
    ]
