from django.urls import path

from . import (
    opj_lifecycle,
    opj_lifecycle_acceptance,
    opj_lifecycle_repair,
    views,
)

app_name = "operational_log"

urlpatterns = [
    path("operations/journal/", views.registry, name="registry"),
    path(
        "operations/journal/<int:journal_id>/shift/",
        views.shift_workspace,
        name="shift_workspace",
    ),
    path(
        "operations/journal/<int:journal_id>/shift/open/",
        views.open_shift_view,
        name="open_shift",
    ),
    path(
        "operations/journal/<int:journal_id>/shift/drafts/add/",
        views.add_draft_entry,
        name="add_draft",
    ),
    path(
        "operations/journal/<int:journal_id>/shift/drafts/register-selected/",
        opj_lifecycle_acceptance.register_drafts_batch_view,
        name="register_drafts_batch",
    ),
    path(
        (
            "operations/journal/<int:journal_id>/shift/drafts/"
            "<uuid:public_id>/autosave/"
        ),
        opj_lifecycle.autosave_draft_guard_view,
        name="autosave_draft",
    ),
    path(
        (
            "operations/journal/<int:journal_id>/shift/drafts/"
            "<uuid:public_id>/register/"
        ),
        opj_lifecycle_acceptance.register_single_draft_view,
        name="register_draft_lifecycle",
    ),
    path(
        (
            "operations/journal/<int:journal_id>/shift/drafts/"
            "<uuid:public_id>/move/"
        ),
        opj_lifecycle.move_draft_guard_view,
        name="move_draft",
    ),
    path(
        (
            "operations/journal/<int:journal_id>/shift/drafts/"
            "<uuid:public_id>/remove/"
        ),
        opj_lifecycle.remove_draft_guard_view,
        name="remove_draft",
    ),
    path(
        (
            "operations/journal/<int:journal_id>/shift/drafts/"
            "<uuid:public_id>/restore/"
        ),
        opj_lifecycle.restore_draft_guard_view,
        name="restore_draft",
    ),
    path(
        "operations/journal/<int:journal_id>/entries/<int:sequence_number>/lifecycle/",
        opj_lifecycle.entry_lifecycle_view,
        name="entry_lifecycle",
    ),
    path(
        "operations/journal/<int:journal_id>/entries/<int:sequence_number>/correct/",
        opj_lifecycle_repair.correct_entry_view,
        name="entry_correct",
    ),
    path(
        "operations/journal/<int:journal_id>/entries/<int:sequence_number>/cancel/",
        opj_lifecycle_repair.cancel_entry_view,
        name="entry_cancel",
    ),
    path(
        "operations/journal/<int:journal_id>/display/",
        views.update_display,
        name="update_display",
    ),
    path(
        "operations/journal/<int:journal_id>/print/",
        opj_lifecycle_acceptance.print_journal_view,
        name="print",
    ),
    path(
        "operations/journal/<int:journal_id>/",
        opj_lifecycle_acceptance.clean_journal_view,
        name="detail",
    ),
]
