# Generated by Django 5.2.16 on 2026-07-14 23:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_normative_registry'),
        ('organizations', '0001_initial_organizational_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Системный код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование вида оборудования')),
                ('category', models.CharField(choices=[('KTP', 'Комплектная трансформаторная подстанция'), ('WTG', 'Ветроэнергетическая установка'), ('SWITCHGEAR', 'Распределительное устройство'), ('SUBSTATION', 'Подстанционное оборудование'), ('LINE', 'Линия электропередачи или кабельная линия'), ('RPA', 'Релейная защита и автоматика'), ('SDTU', 'Средства диспетчерского и технологического управления'), ('AUXILIARY', 'Вспомогательное оборудование'), ('OTHER', 'Другое оборудование')], max_length=24, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name': 'вид оборудования',
                'verbose_name_plural': 'виды оборудования',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DocumentEquipmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_equipment_links', to='organizations.employee', verbose_name='Добавил')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_links', to='documents.document', verbose_name='Документ')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_links', to='documents.documentversion', verbose_name='Версия документа')),
            ],
            options={
                'verbose_name': 'связь документа с оборудованием',
                'verbose_name_plural': 'связи документов с оборудованием',
                'ordering': ('document_version', 'equipment__code'),
            },
        ),
        migrations.CreateModel(
            name='EnergySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Системный код')),
                ('name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('site_type', models.CharField(choices=[('WIND_POWER_PLANT', 'Ветроэлектростанция'), ('SUBSTATION', 'Подстанция'), ('CONTROL_CENTER', 'Диспетчерский или оперативный центр'), ('OTHER', 'Другой энергообъект')], max_length=32, verbose_name='Вид энергообъекта')),
                ('is_external', models.BooleanField(default=False, help_text='Объект учитывается для связей, но не принадлежит эксплуатационному контуру прототипа.', verbose_name='Внешний или смежный объект')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_sites', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'энергообъект',
                'verbose_name_plural': 'энергообъекты',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('code', models.CharField(max_length=96, verbose_name='Стабильный код')),
                ('technical_name', models.CharField(max_length=500, verbose_name='Техническое наименование')),
                ('status', models.CharField(choices=[('ACTIVE', 'В работе'), ('RESERVE', 'Резерв'), ('OUT_OF_SERVICE', 'Выведено из работы'), ('DECOMMISSIONED', 'Выведено из эксплуатации'), ('PROJECT', 'Проектное оборудование')], default='ACTIVE', max_length=24, verbose_name='Состояние')),
                ('voltage_level', models.CharField(blank=True, max_length=64, verbose_name='Класс напряжения')),
                ('commissioned_on', models.DateField(blank=True, null=True, verbose_name='Введено в эксплуатацию')),
                ('decommissioned_on', models.DateField(blank=True, null=True, verbose_name='Выведено из эксплуатации')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные характеристики')),
                ('is_external', models.BooleanField(default=False, verbose_name='Внешнее или смежное оборудование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='organizations.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='equipment.equipmentasset', verbose_name='Родительский объект')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='equipment.energysite', verbose_name='Энергообъект')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='equipment.equipmenttype', verbose_name='Вид оборудования')),
            ],
            options={
                'verbose_name': 'единица оборудования',
                'verbose_name_plural': 'единицы оборудования',
                'ordering': ('site__name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=1000, verbose_name='Алиас')),
                ('normalized_alias', models.CharField(editable=False, max_length=1000, verbose_name='Нормализованный алиас')),
                ('alias_type', models.CharField(choices=[('DISPATCHER', 'Диспетчерский вариант'), ('LEGACY', 'Историческое наименование'), ('ABBREVIATION', 'Сокращение'), ('LOCAL', 'Локальное наименование'), ('SEARCH', 'Поисковый вариант')], max_length=24, verbose_name='Вид алиаса')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('basis_reference', models.CharField(blank=True, max_length=1000, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_aliases', to='organizations.employee', verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_aliases', to='organizations.organization', verbose_name='Организация')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='equipment.equipmentasset', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'алиас оборудования',
                'verbose_name_plural': 'алиасы оборудования',
                'ordering': ('equipment', 'alias'),
            },
        ),
        migrations.CreateModel(
            name='DocumentEquipmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_public_id_snapshot', models.UUIDField(verbose_name='Идентификатор оборудования')),
                ('equipment_code_snapshot', models.CharField(max_length=96, verbose_name='Код оборудования')),
                ('dispatcher_name_snapshot', models.CharField(max_length=1000, verbose_name='Диспетчерское наименование')),
                ('technical_name_snapshot', models.CharField(max_length=500, verbose_name='Техническое наименование')),
                ('equipment_type_code_snapshot', models.CharField(max_length=64, verbose_name='Код вида оборудования')),
                ('equipment_type_name_snapshot', models.CharField(max_length=255, verbose_name='Вид оборудования')),
                ('site_code_snapshot', models.CharField(max_length=64, verbose_name='Код энергообъекта')),
                ('site_name_snapshot', models.CharField(max_length=500, verbose_name='Энергообъект')),
                ('hierarchy_path_snapshot', models.TextField(verbose_name='Иерархический путь')),
                ('name_revision_number_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Редакция диспетчерского наименования')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Зафиксировано сервером')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_snapshots', to='documents.document', verbose_name='Документ')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_snapshots', to='documents.documentversion', verbose_name='Версия документа')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='equipment.documentequipmentlink', verbose_name='Исходная связь')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_snapshots', to='equipment.equipmentasset', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'снимок оборудования документа',
                'verbose_name_plural': 'снимки оборудования документов',
                'ordering': ('document_version', 'equipment_code_snapshot'),
            },
        ),
        migrations.AddField(
            model_name='documentequipmentlink',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='equipment.equipmentasset', verbose_name='Оборудование'),
        ),
        migrations.CreateModel(
            name='EquipmentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NAME_PUBLISHED', 'Опубликовано диспетчерское наименование'), ('DOCUMENT_SNAPSHOT_CREATED', 'Создан снимок оборудования документа')], max_length=40, verbose_name='Событие')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Серверное время')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('actor_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_audit_events', to='organizations.employee', verbose_name='Сотрудник')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_audit_events', to='documents.documentversion', verbose_name='Версия документа')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='equipment.equipmentasset', verbose_name='Оборудование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_audit_events', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'событие аудита оборудования',
                'verbose_name_plural': 'события аудита оборудования',
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentNameRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер редакции')),
                ('dispatcher_name', models.CharField(max_length=1000, verbose_name='Диспетчерское наименование')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Явно действует по')),
                ('basis_reference', models.CharField(blank=True, max_length=1000, verbose_name='Документ-основание')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликовано')], default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликовано')),
                ('digest', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 редакции наименования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_equipment_names', to='organizations.employee', verbose_name='Опубликовал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_name_revisions', to='equipment.equipmentasset', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'редакция диспетчерского наименования',
                'verbose_name_plural': 'редакции диспетчерских наименований',
                'ordering': ('equipment', '-effective_from', '-revision_number'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FEEDS', 'Питает'), ('CONNECTS', 'Соединяет'), ('PROTECTS', 'Защищает'), ('MONITORS', 'Контролирует или передаёт телеметрию'), ('BACKUP_FOR', 'Резервирует'), ('RELATED', 'Связано')], max_length=24, verbose_name='Вид связи')),
                ('description', models.TextField(blank=True, verbose_name='Описание связи')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('basis_reference', models.CharField(blank=True, max_length=1000, verbose_name='Документ-основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_relations', to='organizations.employee', verbose_name='Создал')),
                ('source_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_equipment_relations', to='equipment.equipmentasset', verbose_name='Исходное оборудование')),
                ('target_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_equipment_relations', to='equipment.equipmentasset', verbose_name='Связанное оборудование')),
            ],
            options={
                'verbose_name': 'связь оборудования',
                'verbose_name_plural': 'связи оборудования',
                'ordering': ('source_equipment', 'relation_type', 'target_equipment'),
            },
        ),
        migrations.AddConstraint(
            model_name='energysite',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_energy_site_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='equipmentalias',
            constraint=models.UniqueConstraint(fields=('organization', 'normalized_alias', 'valid_from'), name='uniq_equipment_alias_start_per_org'),
        ),
        migrations.AddConstraint(
            model_name='documentequipmentsnapshot',
            constraint=models.UniqueConstraint(fields=('document_version', 'equipment'), name='uniq_document_equipment_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='documentequipmentlink',
            constraint=models.UniqueConstraint(fields=('document_version', 'equipment'), name='uniq_document_version_equipment'),
        ),
        migrations.AddIndex(
            model_name='equipmentauditevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='equipment_e_organiz_f7f12e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentauditevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='equipment_e_event_t_0447ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentnamerevision',
            constraint=models.UniqueConstraint(fields=('equipment', 'revision_number'), name='uniq_equipment_name_revision'),
        ),
        migrations.AddConstraint(
            model_name='equipmentnamerevision',
            constraint=models.UniqueConstraint(fields=('equipment', 'effective_from'), name='uniq_equipment_name_effective_start'),
        ),
        migrations.AddConstraint(
            model_name='equipmentnamerevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('digest', ''), ('published_at__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('status', 'PUBLISHED'), models.Q(('digest', ''), _negated=True)), _connector='OR'), name='equipment_name_publication_consistent'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrelation',
            constraint=models.UniqueConstraint(fields=('source_equipment', 'target_equipment', 'relation_type', 'valid_from'), name='uniq_equipment_relation_start'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source_equipment', models.F('target_equipment')), _negated=True), name='equipment_relation_not_self'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['organization', 'status', 'code'], name='equipment_e_organiz_92ce64_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['site', 'equipment_type', 'code'], name='equipment_e_site_id_5d4d83_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentasset',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_equipment_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='equipmentasset',
            constraint=models.CheckConstraint(condition=models.Q(('decommissioned_on__isnull', True), ('commissioned_on__isnull', True), ('decommissioned_on__gte', models.F('commissioned_on')), _connector='OR'), name='equipment_lifecycle_window_valid'),
        ),
    ]
