# Generated by Django 5.2.16 on 2026-07-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_equipment_registry'),
        ('organizations', '0006_journal_simplified_time_input'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmentalias',
            name='uniq_equipment_alias_start_per_org',
        ),
        migrations.AddField(
            model_name='equipmentalias',
            name='scope_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_child_aliases', to='equipment.equipmentasset', verbose_name='Область алиаса — родительский объект'),
        ),
        migrations.AddField(
            model_name='equipmentalias',
            name='scope_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_equipment_aliases', to='equipment.energysite', verbose_name='Область алиаса — энергообъект'),
        ),
        migrations.AddConstraint(
            model_name='equipmentalias',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_parent__isnull', True), ('scope_site__isnull', True)), fields=('organization', 'normalized_alias', 'valid_from'), name='uniq_global_equipment_alias_start'),
        ),
        migrations.AddConstraint(
            model_name='equipmentalias',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_parent__isnull', True), ('scope_site__isnull', False)), fields=('organization', 'scope_site', 'normalized_alias', 'valid_from'), name='uniq_site_equipment_alias_start'),
        ),
        migrations.AddConstraint(
            model_name='equipmentalias',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_parent__isnull', False)), fields=('organization', 'scope_parent', 'normalized_alias', 'valid_from'), name='uniq_parent_equipment_alias_start'),
        ),
    ]
