# Generated by Django 5.2.16 on 2026-07-14 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial_organizational_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('number_prefix', models.CharField(max_length=24, verbose_name='Префикс номера')),
                ('number_width', models.PositiveSmallIntegerField(default=6, verbose_name='Разрядность номера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_types', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последнее значение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_number_sequences', to='organizations.organization', verbose_name='Организация')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'серверный нумератор',
                'verbose_name_plural': 'серверные нумераторы',
                'ordering': ('organization__name', 'document_type__name', 'year'),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REGISTERED', 'Зарегистрирован')], db_index=True, default='DRAFT', max_length=24, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('registration_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год регистрации')),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('registration_number', models.CharField(blank=True, max_length=96, verbose_name='Регистрационный номер')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Зарегистрирован')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to='organizations.employee', verbose_name='Автор черновика')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.organization', verbose_name='Организация')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_documents', to='organizations.employee', verbose_name='Зарегистрировал')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REGISTERED', 'Зафиксирована при регистрации')], db_index=True, default='DRAFT', max_length=24, verbose_name='Статус')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Зафиксирована')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_versions', to='organizations.employee', verbose_name='Создал')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document', verbose_name='Документ')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_document_versions', to='organizations.employee', verbose_name='Зафиксировал')),
            ],
            options={
                'verbose_name': 'версия документа',
                'verbose_name_plural': 'версии документов',
                'ordering': ('document', 'version_number'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion', verbose_name='Текущая версия'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DOCUMENT_CREATED', 'Создан черновик'), ('DRAFT_UPDATED', 'Черновик изменён'), ('DOCUMENT_REGISTERED', 'Документ зарегистрирован'), ('DOCUMENT_LINK_CREATED', 'Создана связь документов')], db_index=True, max_length=40, verbose_name='Событие')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Серверное время')),
                ('entity_type', models.CharField(max_length=64, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(max_length=64, verbose_name='Идентификатор сущности')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('actor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_audit_events', to='organizations.employee', verbose_name='Сотрудник')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_audit_events', to='organizations.organization', verbose_name='Организация')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='documents.document', verbose_name='Документ')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='documents.documentversion', verbose_name='Версия документа')),
            ],
            options={
                'verbose_name': 'событие аудита',
                'verbose_name_plural': 'события аудита',
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('RELATED', 'Связанный документ'), ('BASED_ON', 'Создан на основании'), ('CORRECTS', 'Исправляет'), ('SUPERSEDES', 'Заменяет')], max_length=24, verbose_name='Тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_links', to='organizations.employee', verbose_name='Создал связь')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_links', to='documents.document', verbose_name='Исходный документ')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='documents.document', verbose_name='Связанный документ')),
            ],
            options={
                'verbose_name': 'связь документов',
                'verbose_name_plural': 'связи документов',
                'ordering': ('source_document', 'link_type', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('source_document', 'target_document', 'link_type'), name='uniq_typed_document_link'), models.CheckConstraint(condition=models.Q(('source_document', models.F('target_document')), _negated=True), name='document_link_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_document_type_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('organization', 'number_prefix'), name='uniq_document_prefix_per_org'),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.CheckConstraint(condition=models.Q(('number_width__gte', 3), ('number_width__lte', 12)), name='document_type_number_width_range'),
        ),
        migrations.AddConstraint(
            model_name='documentnumbersequence',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'year'), name='uniq_document_sequence_per_type_year'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('registered_at__isnull', True), ('registered_by__isnull', True), ('status', 'DRAFT')), models.Q(('registered_at__isnull', False), ('registered_by__isnull', False), ('status', 'REGISTERED')), _connector='OR'), name='document_version_registration_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='documents_d_organiz_1663e1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['registration_number'], name='documents_d_registr_b72dc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('organization', 'document_type', 'registration_year', 'sequence_number'), name='uniq_document_number_components'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('organization', 'registration_number'), name='uniq_document_registration_number'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('registered_at__isnull', True), ('registered_by__isnull', True), ('registration_number', ''), ('registration_year__isnull', True), ('sequence_number__isnull', True), ('status', 'DRAFT')), models.Q(('registered_at__isnull', False), ('registered_by__isnull', False), ('registration_year__isnull', False), ('sequence_number__isnull', False), ('status', 'REGISTERED'), models.Q(('registration_number', ''), _negated=True)), _connector='OR'), name='document_registration_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='documents_a_organiz_0596ce_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='documents_a_entity__8bdae2_idx'),
        ),
    ]
