# Generated by Django 5.2.16 on 2026-07-14 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial_document_core'),
        ('organizations', '0001_initial_organizational_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_CREATED', 'Создан черновик'), ('DRAFT_UPDATED', 'Черновик изменён'), ('DOCUMENT_REGISTERED', 'Документ зарегистрирован'), ('DOCUMENT_SIGNATURE_CREATED', 'Создано системное подтверждение'), ('LEGACY_SIGNATURE_MIGRATED', 'Создан legacy-маркер миграции'), ('DOCUMENT_LINK_CREATED', 'Создана связь документов')], db_index=True, max_length=40, verbose_name='Событие'),
        ),
        migrations.CreateModel(
            name='SignedSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Регистрация документа')], max_length=32, verbose_name='Назначение')),
                ('schema_version', models.CharField(default='eod.document.registration.v1', editable=False, max_length=64, verbose_name='Версия схемы снимка')),
                ('canonical_json', models.TextField(editable=False, verbose_name='Каноническое JSON-представление')),
                ('hash_algorithm', models.CharField(default='SHA-256', editable=False, max_length=16, verbose_name='Алгоритм контрольной суммы')),
                ('digest', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='SHA-256')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_snapshots', to='documents.document', verbose_name='Документ')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_snapshots', to='documents.documentversion', verbose_name='Версия документа')),
            ],
            options={
                'verbose_name': 'подписываемый снимок',
                'verbose_name_plural': 'подписываемые снимки',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Регистрация документа')], max_length=32, verbose_name='Назначение')),
                ('confirmation_method', models.CharField(choices=[('PASSWORD_REAUTH', 'Повторная аутентификация паролем'), ('LEGACY_MIGRATION', 'Перенесено без повторной аутентификации'), ('DEMO_SEED', 'Демонстрационное системное заполнение')], max_length=32, verbose_name='Способ подтверждения')),
                ('username_snapshot', models.CharField(max_length=150, verbose_name='Имя пользователя на момент подтверждения')),
                ('full_name_snapshot', models.CharField(max_length=500, verbose_name='Ф.И.О. на момент подтверждения')),
                ('position_snapshot', models.CharField(blank=True, max_length=500, verbose_name='Должность на момент подтверждения')),
                ('division_snapshot', models.CharField(blank=True, max_length=500, verbose_name='Подразделение на момент подтверждения')),
                ('workplace_snapshot', models.CharField(blank=True, max_length=500, verbose_name='Рабочее место на момент подтверждения')),
                ('roles_snapshot', models.JSONField(blank=True, default=list, verbose_name='Полномочия на момент подтверждения')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Серверное время подтверждения')),
                ('checksum_algorithm', models.CharField(default='SHA-256', editable=False, max_length=16, verbose_name='Алгоритм контрольной суммы записи')),
                ('checksum', models.CharField(editable=False, max_length=64, verbose_name='Контрольная сумма записи подписи')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to='organizations.employee', verbose_name='Сотрудник')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='documents.signedsnapshot', verbose_name='Подписываемый снимок')),
            ],
            options={
                'verbose_name': 'системное подтверждение',
                'verbose_name_plural': 'системные подтверждения',
                'ordering': ('-signed_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='signedsnapshot',
            constraint=models.UniqueConstraint(fields=('document_version', 'purpose'), name='uniq_signed_snapshot_per_version_purpose'),
        ),
    ]
