# Generated by Django 5.2.16 on 2026-07-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_legacy_signature_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_CREATED', 'Создан черновик'), ('DRAFT_UPDATED', 'Черновик изменён'), ('DOCUMENT_REGISTERED', 'Документ зарегистрирован'), ('DOCUMENT_SIGNATURE_CREATED', 'Создано системное подтверждение'), ('LEGACY_SIGNATURE_MIGRATED', 'Создан признак перенесённого документа'), ('DOCUMENT_LINK_CREATED', 'Создана связь документов')], db_index=True, max_length=40, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='confirmation_method',
            field=models.CharField(choices=[('PASSWORD_REAUTH', 'Повторная аутентификация паролем'), ('LEGACY_MIGRATION', 'Перенос ранее зарегистрированного документа'), ('DEMO_SEED', 'Демонстрационное создание')], max_length=32, verbose_name='Способ подтверждения'),
        ),
    ]
