import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0005_patch_011_5_power_system_asset_importer"),
        ("organizations", "0007_personnel_qualifications_and_operational_rights"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelSourceRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Публичный идентификатор")),
                ("source_reference", models.CharField(max_length=1000, verbose_name="Источник или основание")),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                ("original_filename", models.CharField(max_length=255, verbose_name="Имя XLSX")),
                ("file_size", models.PositiveBigIntegerField(verbose_name="Размер XLSX, байт")),
                ("file_sha256", models.CharField(max_length=64, verbose_name="SHA-256 XLSX")),
                ("sheet_name", models.CharField(max_length=255, verbose_name="Лист")),
                ("layout_version", models.CharField(choices=[("CURRENT_28_COLUMNS", "Текущая матрица с подразделением"), ("LEGACY_22_COLUMNS", "Ранняя матрица без отдельного подразделения")], max_length=32, verbose_name="Версия структуры")),
                ("document_date", models.DateField(blank=True, null=True, verbose_name="Дата документа")),
                ("document_number", models.CharField(blank=True, max_length=255, verbose_name="Номер документа")),
                ("manifest", models.JSONField(default=dict, verbose_name="Манифест разбора")),
                ("footnotes", models.JSONField(default=dict, verbose_name="Сноски источника")),
                ("total_people", models.PositiveIntegerField(default=0, verbose_name="Работников")),
                ("total_authority_cells", models.PositiveIntegerField(default=0, verbose_name="Ячеек полномочий")),
                ("ready_rows", models.PositiveIntegerField(default=0, verbose_name="Готовых строк")),
                ("review_rows", models.PositiveIntegerField(default=0, verbose_name="Строк на проверке")),
                ("blocked_rows", models.PositiveIntegerField(default=0, verbose_name="Заблокированных строк")),
                ("publishable_grants", models.PositiveIntegerField(default=0, verbose_name="Публикуемых прав")),
                ("ambiguous_cells", models.PositiveIntegerField(default=0, verbose_name="Неоднозначных ячеек")),
                ("status", models.CharField(choices=[("STAGED", "Подготовлена к проверке"), ("PARTIALLY_PUBLISHED", "Опубликована частично"), ("PUBLISHED", "Опубликована"), ("DISCARDED", "Убрана из рабочего списка")], db_index=True, default="STAGED", max_length=24, verbose_name="Состояние")),
                ("publication_digest", models.CharField(blank=True, editable=False, max_length=64, verbose_name="SHA-256 публикации")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Опубликовано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменено")),
                ("discarded_at", models.DateTimeField(blank=True, null=True, verbose_name="Убрано из рабочего списка")),
                ("data_profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="personnel_source_revisions", to="imports.dataprofile", verbose_name="Профиль данных")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="personnel_source_revisions", to="organizations.organization", verbose_name="Организация")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="published_personnel_revisions", to="organizations.employee", verbose_name="Опубликовал")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_personnel_revisions", to="organizations.employee", verbose_name="Загрузил")),
            ],
            options={"verbose_name": "редакция источника персонала и прав", "verbose_name_plural": "редакции источников персонала и прав", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="PersonnelSourceRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_row_number", models.PositiveIntegerField(verbose_name="Строка XLSX")),
                ("source_sequence", models.PositiveIntegerField(verbose_name="Номер по источнику")),
                ("full_name_raw", models.CharField(max_length=500, verbose_name="ФИО из источника")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="Имя")),
                ("middle_name", models.CharField(blank=True, max_length=150, verbose_name="Отчество")),
                ("position_raw", models.CharField(max_length=500, verbose_name="Должность из источника")),
                ("division_raw", models.CharField(blank=True, max_length=500, verbose_name="Подразделение из источника")),
                ("personnel_category_raw", models.CharField(blank=True, max_length=128, verbose_name="Категория персонала")),
                ("electrical_safety_raw", models.CharField(blank=True, max_length=500, verbose_name="Группа и класс напряжения")),
                ("electrical_safety_group", models.CharField(blank=True, max_length=16, verbose_name="Группа")),
                ("voltage_scope", models.CharField(blank=True, max_length=255, verbose_name="Класс напряжения")),
                ("installation_scope_raw", models.TextField(blank=True, verbose_name="Область электроустановок")),
                ("rza_category_raw", models.CharField(blank=True, max_length=128, verbose_name="Категория РЗА")),
                ("match_kind", models.CharField(choices=[("NONE", "Совпадение не найдено"), ("EXACT", "Однозначное точное совпадение"), ("REVIEW_REQUIRED", "Совпадение требует проверки")], default="NONE", max_length=24, verbose_name="Результат сопоставления")),
                ("review_status", models.CharField(choices=[("READY", "Готова"), ("REVIEW_REQUIRED", "Требует проверки"), ("BLOCKED", "Заблокирована"), ("PUBLISHED", "Опубликована"), ("EXCLUDED", "Исключена")], db_index=True, max_length=24, verbose_name="Состояние проверки")),
                ("issues", models.JSONField(blank=True, default=list, verbose_name="Проблемы строки")),
                ("fingerprint", models.CharField(max_length=64, verbose_name="SHA-256 строки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("matched_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="matched_personnel_source_rows", to="organizations.employee", verbose_name="Предполагаемый сотрудник")),
                ("published_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="published_personnel_source_rows", to="organizations.employee", verbose_name="Опубликованный сотрудник")),
                ("source_revision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="person_rows", to="imports.personnelsourcerevision", verbose_name="Редакция источника")),
            ],
            options={"verbose_name": "строка источника персонала", "verbose_name_plural": "строки источника персонала", "ordering": ("source_revision", "source_row_number")},
        ),
        migrations.CreateModel(
            name="PersonnelAuthorityCell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_column", models.CharField(max_length=8, verbose_name="Колонка XLSX")),
                ("source_header", models.CharField(max_length=500, verbose_name="Заголовок источника")),
                ("raw_marker", models.CharField(blank=True, max_length=500, verbose_name="Исходная отметка")),
                ("grant_state", models.CharField(choices=[("GRANTED", "Право предоставлено"), ("NOT_GRANTED", "Право не предоставлено"), ("BLANK", "Значение отсутствует"), ("QUALIFIED", "Право с квалификатором"), ("AMBIGUOUS", "Неоднозначное значение")], max_length=16, verbose_name="Состояние")),
                ("qualifier", models.CharField(blank=True, max_length=500, verbose_name="Квалификатор")),
                ("footnote_numbers", models.JSONField(blank=True, default=list, verbose_name="Номера сносок")),
                ("equipment_groups", models.JSONField(blank=True, default=list, verbose_name="Группы оборудования")),
                ("issues", models.JSONField(blank=True, default=list, verbose_name="Проблемы ячейки")),
                ("is_publishable", models.BooleanField(default=False, verbose_name="Можно опубликовать автоматически")),
                ("person_row", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="authority_cells", to="imports.personnelsourcerow", verbose_name="Строка работника")),
                ("right_definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="source_cells", to="organizations.operationalrightdefinition", verbose_name="Вид права")),
            ],
            options={"verbose_name": "ячейка полномочия", "verbose_name_plural": "ячейки полномочий", "ordering": ("person_row", "right_definition__display_order")},
        ),
        migrations.CreateModel(
            name="PersonnelPublication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Публичный идентификатор")),
                ("schema_version", models.CharField(default="eod.personnel-authority.publication.v1", max_length=64, verbose_name="Версия схемы")),
                ("canonical_json", models.TextField(verbose_name="Канонический снимок публикации")),
                ("digest", models.CharField(max_length=64, unique=True, verbose_name="SHA-256 публикации")),
                ("result_summary", models.JSONField(default=dict, verbose_name="Итоги публикации")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Опубликовано")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="personnel_publications", to="organizations.employee", verbose_name="Опубликовал")),
                ("source_revision", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="publication", to="imports.personnelsourcerevision", verbose_name="Редакция источника")),
            ],
            options={"verbose_name": "публикация персонала и полномочий", "verbose_name_plural": "публикации персонала и полномочий", "ordering": ("-created_at", "-id")},
        ),
        migrations.AddConstraint(model_name="personnelsourcerevision", constraint=models.UniqueConstraint(fields=("organization", "file_sha256"), name="uniq_personnel_source_sha_org")),
        migrations.AddIndex(model_name="personnelsourcerevision", index=models.Index(fields=["organization", "status", "-created_at"], name="personnel_src_status_idx")),
        migrations.AddConstraint(model_name="personnelsourcerow", constraint=models.UniqueConstraint(fields=("source_revision", "source_row_number"), name="uniq_personnel_source_row")),
        migrations.AddConstraint(model_name="personnelauthoritycell", constraint=models.UniqueConstraint(fields=("person_row", "right_definition"), name="uniq_personnel_authority_cell")),
    ]
