# Generated by Django 5.2.16 on 2026-07-14 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial_organizational_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, unique=True, verbose_name='Системный код')),
                ('title', models.CharField(max_length=1000, verbose_name='Полное наименование')),
                ('short_title', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('scope', models.CharField(choices=[('FEDERAL', 'Федеральный нормативный документ'), ('INDUSTRY', 'Отраслевой нормативный документ'), ('LOCAL', 'Локальный документ организации')], max_length=24, verbose_name='Уровень документа')),
                ('issuer', models.CharField(max_length=500, verbose_name='Издатель')),
                ('document_number', models.CharField(blank=True, max_length=128, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется в реестре')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normative_documents', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'нормативный документ',
                'verbose_name_plural': 'нормативные документы',
                'ordering': ('scope', 'short_title', 'title'),
            },
        ),
        migrations.CreateModel(
            name='NormativeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер редакции')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликована')], db_index=True, default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('source_reference', models.CharField(blank=True, max_length=1000, verbose_name='Источник или ссылка на оригинал')),
                ('change_summary', models.TextField(blank=True, verbose_name='Описание редакции')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликована')),
                ('digest', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 опубликованной редакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_normative_revisions', to='organizations.employee', verbose_name='Опубликовал')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='normatives.normativedocument', verbose_name='Нормативный документ')),
            ],
            options={
                'verbose_name': 'редакция нормативного документа',
                'verbose_name_plural': 'редакции нормативных документов',
                'ordering': ('document', '-revision_number'),
            },
        ),
        migrations.CreateModel(
            name='NormativeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=96, verbose_name='Код требования')),
                ('clause', models.CharField(max_length=128, verbose_name='Пункт документа')),
                ('title', models.CharField(max_length=500, verbose_name='Краткое содержание')),
                ('requirement_text', models.TextField(verbose_name='Требование')),
                ('applicability_text', models.TextField(blank=True, verbose_name='Область применимости')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательное требование')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='normatives.normativerevision', verbose_name='Редакция')),
            ],
            options={
                'verbose_name': 'нормативное требование',
                'verbose_name_plural': 'нормативные требования',
                'ordering': ('revision', 'display_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationConfigurationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер редакции')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('configuration', models.JSONField(default=dict, verbose_name='Конфигурация организации')),
                ('change_summary', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликована')], default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликована')),
                ('digest', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 опубликованной конфигурации')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_configuration_revisions', to='organizations.employee', verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_revisions', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'редакция конфигурации организации',
                'verbose_name_plural': 'редакции конфигурации организаций',
                'ordering': ('organization', '-revision_number'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationNameRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('basis_reference', models.CharField(blank=True, max_length=1000, verbose_name='Документ-основание')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликована')], default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликована')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_organization_name_revisions', to='organizations.employee', verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_revisions', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'историческое наименование организации',
                'verbose_name_plural': 'исторические наименования организаций',
                'ordering': ('organization', '-valid_from'),
            },
        ),
        migrations.CreateModel(
            name='RequirementTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_code', models.CharField(max_length=128, verbose_name='Код функции')),
                ('function_name', models.CharField(max_length=500, verbose_name='Функция системы')),
                ('implementation_status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('IMPLEMENTED', 'Реализовано'), ('VERIFIED', 'Проверено'), ('NOT_APPLICABLE', 'Не применяется')], default='PLANNED', max_length=24, verbose_name='Состояние реализации')),
                ('test_reference', models.CharField(blank=True, max_length=500, verbose_name='Автоматический тест')),
                ('acceptance_scenario', models.TextField(blank=True, verbose_name='Приёмочный сценарий')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Зафиксировано')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traces', to='normatives.normativerequirement', verbose_name='Нормативное требование')),
            ],
            options={
                'verbose_name': 'трассировка требования',
                'verbose_name_plural': 'трассировки требований',
                'ordering': ('requirement', 'function_code', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='normativerevision',
            constraint=models.UniqueConstraint(fields=('document', 'revision_number'), name='uniq_normative_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='normativerevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('digest', ''), ('published_at__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('status', 'PUBLISHED'), models.Q(('digest', ''), _negated=True)), _connector='OR'), name='normative_revision_publication_consistent'),
        ),
        migrations.AddConstraint(
            model_name='normativerequirement',
            constraint=models.UniqueConstraint(fields=('revision', 'code'), name='uniq_requirement_code_per_revision'),
        ),
        migrations.AddConstraint(
            model_name='organizationconfigurationrevision',
            constraint=models.UniqueConstraint(fields=('organization', 'revision_number'), name='uniq_organization_configuration_revision'),
        ),
        migrations.AddConstraint(
            model_name='organizationconfigurationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('digest', ''), ('published_at__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('status', 'PUBLISHED'), models.Q(('digest', ''), _negated=True)), _connector='OR'), name='organization_configuration_publication_consistent'),
        ),
        migrations.AddConstraint(
            model_name='organizationnamerevision',
            constraint=models.UniqueConstraint(fields=('organization', 'valid_from'), name='uniq_organization_name_revision_start'),
        ),
        migrations.AddConstraint(
            model_name='organizationnamerevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('status', 'PUBLISHED')), _connector='OR'), name='organization_name_publication_consistent'),
        ),
    ]
