# Generated by Django 5.2.16 on 2026-08-01 19:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normatives", "0001_normative_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalModeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=128, verbose_name="Код решения")),
                ("module_id", models.CharField(db_index=True, max_length=128, verbose_name="Код модуля")),
                ("subject_label", models.CharField(max_length=500, verbose_name="Предмет решения")),
                (
                    "product_target_mode",
                    models.CharField(
                        choices=[
                            ("ELECTRONIC_ORIGINAL_TARGET", "Электронный оригинал — целевой режим"),
                            ("HYBRID", "Гибридный режим"),
                            ("PAPER_MIRROR", "Бумажный оригинал с электронной копией"),
                            ("EVIDENCE_EVENT", "Отдельное evidence-событие"),
                            ("REFERENCE_ONLY", "Только справочное использование"),
                            ("POST_DEMO", "После демонстрационного этапа"),
                        ],
                        max_length=40,
                        verbose_name="Целевой продуктовый режим",
                    ),
                ),
                (
                    "proven_legal_mode",
                    models.CharField(
                        choices=[
                            ("ELECTRONIC_ORIGINAL", "Электронный оригинал доказан"),
                            ("HYBRID", "Гибридный режим"),
                            ("PAPER_MIRROR", "Бумажный оригинал с электронной копией"),
                            ("REFERENCE_ONLY", "Только справочное использование"),
                            ("VERIFY", "Требует проверки"),
                        ],
                        db_index=True,
                        default="VERIFY",
                        max_length=32,
                        verbose_name="Доказанный правовой режим",
                    ),
                ),
                (
                    "normative_evidence_status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Подтверждено"),
                            ("PARTIAL", "Подтверждено частично"),
                            ("VERIFY", "Требует проверки"),
                            ("NOT_APPLICABLE", "Не применяется"),
                        ],
                        default="VERIFY",
                        max_length=24,
                        verbose_name="Статус нормативного evidence",
                    ),
                ),
                (
                    "local_act_status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Подтверждено"),
                            ("VERIFY", "Требует проверки"),
                            ("NOT_REQUIRED", "Не требуется"),
                        ],
                        default="VERIFY",
                        max_length=24,
                        verbose_name="Статус локального акта",
                    ),
                ),
                (
                    "normative_basis_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=256,
                        verbose_name="Снимок кода нормативного основания",
                    ),
                ),
                (
                    "local_act_revision_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=256,
                        verbose_name="Снимок кода локального акта",
                    ),
                ),
                ("source_ids", models.JSONField(default=list, verbose_name="Traceable source IDs")),
                ("decision_basis", models.TextField(blank=True, verbose_name="Основание решения")),
                (
                    "decision_maker_snapshot",
                    models.JSONField(default=dict, verbose_name="Снимок автора решения"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Серверное время решения",
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="eod.normative.legal-mode-decision-record.v1",
                        editable=False,
                        max_length=64,
                        verbose_name="Версия схемы",
                    ),
                ),
                (
                    "canonical_json",
                    models.TextField(editable=False, verbose_name="Канонический снимок решения"),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        default="SHA-256",
                        editable=False,
                        max_length=16,
                        verbose_name="Алгоритм контроля целостности",
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=64,
                        verbose_name="SHA-256 решения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Создано"),
                ),
                (
                    "decision_maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_mode_decisions",
                        to="organizations.employee",
                        verbose_name="Зафиксировал решение",
                    ),
                ),
                (
                    "local_act_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="local_act_legal_mode_decisions",
                        to="normatives.normativerevision",
                        verbose_name="Редакция локального акта",
                    ),
                ),
                (
                    "normative_basis_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_mode_basis_decisions",
                        to="normatives.normativerevision",
                        verbose_name="Нормативная редакция-основание",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_mode_decisions",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="normatives.legalmodedecision",
                        verbose_name="Заменяет решение",
                    ),
                ),
            ],
            options={
                "verbose_name": "решение о правовом режиме",
                "verbose_name_plural": "решения о правовых режимах",
                "ordering": ("code", "-decided_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="EvidenceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SIGNATURE", "Подпись / системное подтверждение"),
                            ("ACKNOWLEDGEMENT", "Ознакомление"),
                            ("INSTRUCTION", "Инструктаж"),
                            ("KNOWLEDGE_CHECK", "Проверка знаний"),
                            ("ACTION_CONFIRMATION", "Подтверждение действия"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Тип evidence-события",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(db_index=True, max_length=128, verbose_name="Тип предмета"),
                ),
                (
                    "subject_id",
                    models.CharField(
                        db_index=True,
                        max_length=192,
                        verbose_name="Идентификатор предмета",
                    ),
                ),
                ("actor_snapshot", models.JSONField(default=dict, verbose_name="Снимок участника")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Серверное время события",
                    ),
                ),
                (
                    "confirmation_method",
                    models.CharField(
                        choices=[
                            ("PASSWORD_REAUTH", "Повторная аутентификация паролем"),
                            ("SESSION_AUTH", "Действующая персональная сессия"),
                            ("LEGACY_MIGRATION", "Перенос ранее созданного подтверждения"),
                            ("DEMO_SEED", "Демонстрационное создание"),
                        ],
                        max_length=32,
                        verbose_name="Способ подтверждения",
                    ),
                ),
                (
                    "requires_reauthentication",
                    models.BooleanField(
                        default=False,
                        verbose_name="Требовалась повторная аутентификация",
                    ),
                ),
                (
                    "normative_basis_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=256,
                        verbose_name="Снимок кода нормативного основания",
                    ),
                ),
                ("source_ids", models.JSONField(default=list, verbose_name="Traceable source IDs")),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        max_length=192,
                        verbose_name="Корреляционный идентификатор",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Evidence payload")),
                (
                    "document_signature_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Связанное системное подтверждение документа",
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="eod.evidence.event-record.v1",
                        editable=False,
                        max_length=64,
                        verbose_name="Версия схемы",
                    ),
                ),
                (
                    "canonical_json",
                    models.TextField(editable=False, verbose_name="Канонический снимок события"),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        default="SHA-256",
                        editable=False,
                        max_length=16,
                        verbose_name="Алгоритм контроля целостности",
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=64,
                        verbose_name="SHA-256 события",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Создано"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="organizations.employee",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "corrects_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="normatives.evidenceevent",
                        verbose_name="Исправляет событие",
                    ),
                ),
                (
                    "normative_basis_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="normatives.normativerevision",
                        verbose_name="Нормативная редакция-основание",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidence-событие",
                "verbose_name_plural": "evidence-события",
                "ordering": ("-occurred_at", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="legalmodedecision",
            index=models.Index(
                fields=["organization", "code", "-decided_at"],
                name="norm_legal_org_code_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legalmodedecision",
            index=models.Index(
                fields=["module_id", "proven_legal_mode"],
                name="norm_legal_module_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceevent",
            index=models.Index(
                fields=["organization", "subject_type", "subject_id", "-occurred_at"],
                name="norm_evid_subject_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceevent",
            index=models.Index(
                fields=["organization", "event_type", "-occurred_at"],
                name="norm_evid_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.UniqueConstraint(
                condition=~models.Q(correlation_id=""),
                fields=("organization", "correlation_id"),
                name="uniq_evidence_correlation_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(event_type="SIGNATURE"),
                fields=("document_signature_id",),
                name="uniq_evidence_event_per_doc_signature",
            ),
        ),
    ]
