# Generated by Django 5.2.16 on 2026-07-15 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_normative_registry'),
        ('equipment', '0001_equipment_registry'),
        ('organizations', '0001_initial_organizational_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentSubjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, verbose_name='Системный код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjacent_subject_relations', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'взаимодействие смежных субъектов',
                'verbose_name_plural': 'взаимодействия смежных субъектов',
                'ordering': ('organization__name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AdjacentSubjectRelationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер редакции')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('interaction_scope', models.TextField(verbose_name='Область взаимодействия')),
                ('communication_rules', models.TextField(verbose_name='Правила взаимодействия')),
                ('basis_reference', models.CharField(max_length=1000, verbose_name='Реквизиты документа-основания')),
                ('change_summary', models.TextField(blank=True, verbose_name='Содержание изменения')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликовано')], db_index=True, default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликовано')),
                ('digest', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 редакции взаимодействия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('basis_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjacent_relation_basis_revisions', to='documents.document', verbose_name='Документ-основание в системе')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_adjacent_relation_revisions', to='organizations.employee', verbose_name='Опубликовал')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='dispatching.adjacentsubjectrelation', verbose_name='Связь смежных субъектов')),
            ],
            options={
                'verbose_name': 'редакция взаимодействия смежных субъектов',
                'verbose_name_plural': 'редакции взаимодействия смежных субъектов',
                'ordering': ('relation', '-effective_from', '-revision_number'),
            },
        ),
        migrations.CreateModel(
            name='DispatchLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, verbose_name='Системный код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование уровня')),
                ('level_type', models.CharField(choices=[('DISPATCH', 'Диспетчерский уровень'), ('TECHNOLOGICAL', 'Технологический уровень')], max_length=24, verbose_name='Тип уровня')),
                ('rank', models.PositiveIntegerField(default=100, help_text='Меньшее число означает более высокий уровень.', verbose_name='Порядок уровня')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_levels', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'уровень управления или ведения',
                'verbose_name_plural': 'уровни управления и ведения',
                'ordering': ('organization__name', 'rank', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DispatchSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, verbose_name='Системный код')),
                ('name', models.CharField(max_length=1000, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('subject_type', models.CharField(choices=[('INTERNAL', 'Субъект организации'), ('HIGHER', 'Вышестоящий субъект'), ('ADJACENT', 'Смежный субъект'), ('OTHER', 'Другой субъект')], max_length=24, verbose_name='Вид субъекта')),
                ('is_external', models.BooleanField(default=False, verbose_name='Внешний субъект')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_subjects', to='organizations.organization', verbose_name='Организация-владелец реестра')),
            ],
            options={
                'verbose_name': 'субъект управления или ведения',
                'verbose_name_plural': 'субъекты управления и ведения',
                'ordering': ('organization__name', 'subject_type', 'name'),
            },
        ),
        migrations.AddField(
            model_name='adjacentsubjectrelation',
            name='source_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_adjacent_relations', to='dispatching.dispatchsubject', verbose_name='Первый субъект'),
        ),
        migrations.AddField(
            model_name='adjacentsubjectrelation',
            name='target_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_adjacent_relations', to='dispatching.dispatchsubject', verbose_name='Смежный субъект'),
        ),
        migrations.CreateModel(
            name='ManagementObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='management_object', to='equipment.equipmentasset', verbose_name='Оборудование — объект управления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_objects', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'объект управления',
                'verbose_name_plural': 'объекты управления',
                'ordering': ('organization__name', 'equipment__code'),
            },
        ),
        migrations.CreateModel(
            name='ManagementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер редакции')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('basis_reference', models.CharField(max_length=1000, verbose_name='Реквизиты документа-основания')),
                ('change_summary', models.TextField(blank=True, verbose_name='Содержание изменения')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликовано')], db_index=True, default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликовано')),
                ('digest', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 редакции управления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('basis_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_basis_revisions', to='documents.document', verbose_name='Документ-основание в системе')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_revisions', to='dispatching.dispatchlevel', verbose_name='Уровень управления')),
                ('management_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='dispatching.managementobject', verbose_name='Объект управления')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_management_revisions', to='organizations.employee', verbose_name='Опубликовал')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_revisions', to='dispatching.dispatchsubject', verbose_name='Управляющий субъект')),
            ],
            options={
                'verbose_name': 'редакция управления',
                'verbose_name_plural': 'редакции управления',
                'ordering': ('management_object', '-effective_from', '-revision_number'),
            },
        ),
        migrations.CreateModel(
            name='SupervisionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_object', to='equipment.equipmentasset', verbose_name='Оборудование — объект ведения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_objects', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'объект ведения',
                'verbose_name_plural': 'объекты ведения',
                'ordering': ('organization__name', 'equipment__code'),
            },
        ),
        migrations.CreateModel(
            name='SupervisionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер редакции')),
                ('is_information_only', models.BooleanField(default=False, help_text='Субъект получает сведения, но не осуществляет оперативное ведение режима.', verbose_name='Информационное ведение')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('basis_reference', models.CharField(max_length=1000, verbose_name='Реквизиты документа-основания')),
                ('change_summary', models.TextField(blank=True, verbose_name='Содержание изменения')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликовано')], db_index=True, default='DRAFT', max_length=16, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликовано')),
                ('digest', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 редакции ведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('basis_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervision_basis_revisions', to='documents.document', verbose_name='Документ-основание в системе')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_revisions', to='dispatching.dispatchlevel', verbose_name='Уровень ведения')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_supervision_revisions', to='organizations.employee', verbose_name='Опубликовал')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_revisions', to='dispatching.dispatchsubject', verbose_name='Субъект ведения')),
                ('supervision_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='dispatching.supervisionobject', verbose_name='Объект ведения')),
            ],
            options={
                'verbose_name': 'редакция ведения',
                'verbose_name_plural': 'редакции ведения',
                'ordering': ('supervision_object', '-effective_from', '-revision_number'),
            },
        ),
        migrations.CreateModel(
            name='DispatchingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MANAGEMENT_PUBLISHED', 'Опубликовано управление'), ('SUPERVISION_PUBLISHED', 'Опубликовано ведение'), ('ADJACENCY_PUBLISHED', 'Опубликовано взаимодействие')], max_length=40, verbose_name='Событие')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зафиксировано')),
                ('actor_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatching_audit_events', to='organizations.employee', verbose_name='Сотрудник')),
                ('adjacent_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='dispatching.adjacentsubjectrelationrevision', verbose_name='Редакция взаимодействия')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatching_audit_events', to='organizations.organization', verbose_name='Организация')),
                ('management_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='dispatching.managementrevision', verbose_name='Редакция управления')),
                ('supervision_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='dispatching.supervisionrevision', verbose_name='Редакция ведения')),
            ],
            options={
                'verbose_name': 'событие аудита управления и ведения',
                'verbose_name_plural': 'события аудита управления и ведения',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='adjacentsubjectrelationrevision',
            constraint=models.UniqueConstraint(fields=('relation', 'revision_number'), name='uniq_adjacent_relation_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='adjacentsubjectrelationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('digest', ''), ('published_at__isnull', True), ('published_by__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status', 'PUBLISHED'), models.Q(('digest', ''), _negated=True)), _connector='OR'), name='adjacent_relation_publication_consistent'),
        ),
        migrations.AddConstraint(
            model_name='dispatchlevel',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_dispatch_level_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsubject',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_dispatch_subject_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='adjacentsubjectrelation',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_adjacent_relation_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='adjacentsubjectrelation',
            constraint=models.UniqueConstraint(fields=('organization', 'source_subject', 'target_subject'), name='uniq_directed_adjacent_subject_relation'),
        ),
        migrations.AddConstraint(
            model_name='adjacentsubjectrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject', models.F('target_subject')), _negated=True), name='adjacent_subjects_must_differ'),
        ),
        migrations.AddIndex(
            model_name='managementrevision',
            index=models.Index(fields=['management_object', 'level', 'status', 'effective_from'], name='dispatching_managem_db38da_idx'),
        ),
        migrations.AddConstraint(
            model_name='managementrevision',
            constraint=models.UniqueConstraint(fields=('management_object', 'revision_number'), name='uniq_management_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='managementrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('digest', ''), ('published_at__isnull', True), ('published_by__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status', 'PUBLISHED'), models.Q(('digest', ''), _negated=True)), _connector='OR'), name='management_publication_consistent'),
        ),
        migrations.AddIndex(
            model_name='supervisionrevision',
            index=models.Index(fields=['supervision_object', 'level', 'status', 'effective_from'], name='dispatching_supervi_4cc142_idx'),
        ),
        migrations.AddConstraint(
            model_name='supervisionrevision',
            constraint=models.UniqueConstraint(fields=('supervision_object', 'revision_number'), name='uniq_supervision_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='supervisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('digest', ''), ('published_at__isnull', True), ('published_by__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status', 'PUBLISHED'), models.Q(('digest', ''), _negated=True)), _connector='OR'), name='supervision_publication_consistent'),
        ),
    ]
