# Generated by Django 5.2.16 on 2026-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_management_and_supervision'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionrevision',
            name='conduct_mode',
            field=models.CharField(choices=[('OPERATIONAL', 'Оперативное ведение'), ('INFORMATIONAL', 'Информационное ведение'), ('UNKNOWN', 'Режим ведения не подтверждён')], default='OPERATIONAL', help_text='UNKNOWN сохраняет неопределённость источника без ложного вывода.', max_length=16, verbose_name='Режим ведения'),
        ),
        migrations.AlterField(
            model_name='supervisionrevision',
            name='is_information_only',
            field=models.BooleanField(default=False, help_text='Синхронизируется с режимом ведения и сохраняется для обратной совместимости.', verbose_name='Информационное ведение (совместимость)'),
        ),
    ]
