# Generated by Django 5.2 on 2026-07-17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0004_normative_registry"),
        ("equipment", "0001_equipment_registry"),
        ("organizations", "0003_operational_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=96, verbose_name="Код журнала")),
                (
                    "title",
                    models.CharField(
                        max_length=500, verbose_name="Наименование журнала"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Действующий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_journals",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_journals",
                        to="organizations.workplace",
                        verbose_name="Рабочее место",
                    ),
                ),
            ],
            options={
                "verbose_name": "оперативный журнал",
                "verbose_name_plural": "оперативные журналы",
                "ordering": ("organization__name", "workplace__name", "title"),
            },
        ),
        migrations.CreateModel(
            name="OperationalJournalSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_value",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Последний номер"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="number_sequence",
                        to="operational_log.operationaljournal",
                        verbose_name="Оперативный журнал",
                    ),
                ),
            ],
            options={
                "verbose_name": "нумератор оперативного журнала",
                "verbose_name_plural": "нумераторы оперативных журналов",
            },
        ),
        migrations.CreateModel(
            name="OperationalLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveBigIntegerField(verbose_name="Номер записи"),
                ),
                (
                    "event_at",
                    models.DateTimeField(db_index=True, verbose_name="Время события"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Время регистрации",
                    ),
                ),
                (
                    "entry_form",
                    models.CharField(
                        choices=[
                            ("FREE_TEXT", "Свободная запись"),
                            ("TYPED", "Типизированная запись"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Форма записи",
                    ),
                ),
                (
                    "type_code",
                    models.SlugField(
                        blank=True, max_length=96, verbose_name="Код типа"
                    ),
                ),
                (
                    "type_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование типа"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "typed_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Типизированные данные"
                    ),
                ),
                (
                    "author_full_name_snapshot",
                    models.CharField(
                        editable=False, max_length=500, verbose_name="Ф.И.О. автора"
                    ),
                ),
                (
                    "author_position_snapshot",
                    models.CharField(
                        editable=False, max_length=500, verbose_name="Должность автора"
                    ),
                ),
                (
                    "author_workplace_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        verbose_name="Рабочее место автора",
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="SHA-256 записи"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_log_entries",
                        to="organizations.employee",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="operational_log.operationaljournal",
                        verbose_name="Оперативный журнал",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись оперативного журнала",
                "verbose_name_plural": "записи оперативного журнала",
                "ordering": ("-sequence_number", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["journal", "-sequence_number"],
                        name="operational_journal_fe108e_idx",
                    ),
                    models.Index(
                        fields=["journal", "event_at"],
                        name="operational_journal_da1057_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationalLogEquipmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_code_snapshot",
                    models.CharField(
                        editable=False, max_length=96, verbose_name="Код оборудования"
                    ),
                ),
                (
                    "dispatcher_name_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=1000,
                        verbose_name="Диспетчерское наименование",
                    ),
                ),
                (
                    "site_name_snapshot",
                    models.CharField(
                        editable=False, max_length=500, verbose_name="Энергообъект"
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_links",
                        to="operational_log.operationallogentry",
                        verbose_name="Запись журнала",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_log_links",
                        to="equipment.equipmentasset",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "связь записи журнала с оборудованием",
                "verbose_name_plural": "связи записей журнала с оборудованием",
                "ordering": (
                    "entry",
                    "dispatcher_name_snapshot",
                    "equipment_code_snapshot",
                ),
            },
        ),
        migrations.CreateModel(
            name="OperationalLogDocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=96,
                        verbose_name="Регистрационный номер",
                    ),
                ),
                (
                    "title_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        verbose_name="Заголовок документа",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_log_links",
                        to="documents.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="operational_log.operationallogentry",
                        verbose_name="Запись журнала",
                    ),
                ),
            ],
            options={
                "verbose_name": "связь записи журнала с документом",
                "verbose_name_plural": "связи записей журнала с документами",
                "ordering": ("entry", "registration_number_snapshot"),
            },
        ),
        migrations.CreateModel(
            name="OperationalLogAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("ENTRY_REGISTERED", "Запись зарегистрирована")],
                        max_length=32,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Время события",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="Снимок записи"
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="SHA-256 события"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_log_audit_events",
                        to="organizations.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="operational_log.operationallogentry",
                        verbose_name="Запись журнала",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие оперативного журнала",
                "verbose_name_plural": "события оперативного журнала",
                "ordering": ("-event_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="operationaljournal",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_operational_journal_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationallogentry",
            constraint=models.UniqueConstraint(
                fields=("journal", "sequence_number"),
                name="uniq_operational_log_sequence_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationallogentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence_number__gte", 1)),
                name="operational_log_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationallogentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_at__lte", models.F("registered_at"))),
                name="operational_log_event_not_after_registration",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationallogequipmentlink",
            constraint=models.UniqueConstraint(
                fields=("entry", "equipment"),
                name="uniq_operational_log_entry_equipment",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationallogdocumentlink",
            constraint=models.UniqueConstraint(
                fields=("entry", "document"), name="uniq_operational_log_entry_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationallogauditevent",
            constraint=models.UniqueConstraint(
                fields=("entry", "event_type"), name="uniq_operational_log_entry_event"
            ),
        ),
    ]
