# Generated by Django 5.2.16 on 2026-07-17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operational_log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Открыта"),
                            (
                                "HANDOVER_PREPARATION",
                                "Подготовка к сдаче",
                            ),
                            ("CLOSED", "Закрыта"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=32,
                        verbose_name="Состояние смены",
                    ),
                ),
                (
                    "planned_start_at",
                    models.DateTimeField(verbose_name="Плановое начало"),
                ),
                (
                    "planned_end_at",
                    models.DateTimeField(
                        verbose_name="Плановое окончание"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Фактическое открытие",
                    ),
                ),
                (
                    "opened_by_full_name_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        verbose_name="Ф.И.О. открывшего смену",
                    ),
                ),
                (
                    "opened_by_position_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        verbose_name="Должность открывшего смену",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Фактическое закрытие",
                    ),
                ),
                (
                    "version",
                    models.PositiveBigIntegerField(
                        default=1,
                        verbose_name="Версия смены",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Создана",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Изменена",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="operational_log.operationaljournal",
                        verbose_name="Оперативный журнал",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_operational_shifts",
                        to="organizations.employee",
                        verbose_name="Смену открыл",
                    ),
                ),
            ],
            options={
                "verbose_name": "оперативная смена",
                "verbose_name_plural": "оперативные смены",
                "ordering": ("-planned_start_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["journal", "status"],
                        name="op_shift_journal_status_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationalShiftMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_full_name_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        verbose_name="Ф.И.О. сотрудника",
                    ),
                ),
                (
                    "employee_position_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        verbose_name="Должность сотрудника",
                    ),
                ),
                (
                    "is_shift_lead",
                    models.BooleanField(
                        default=False,
                        verbose_name="Старший смены",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Включён в смену",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_shift_memberships",
                        to="organizations.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="operational_log.operationalshift",
                        verbose_name="Оперативная смена",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник оперативной смены",
                "verbose_name_plural": "участники оперативной смены",
                "ordering": (
                    "-is_shift_lead",
                    "employee_full_name_snapshot",
                    "pk",
                ),
            },
        ),
        migrations.CreateModel(
            name="OperationalDraftEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        verbose_name="Позиция в черновике"
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Время события",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        verbose_name="Содержание",
                    ),
                ),
                (
                    "version",
                    models.PositiveBigIntegerField(
                        default=1,
                        verbose_name="Версия записи",
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Убрана из черновика",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Создана",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Сохранена",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_operational_drafts",
                        to="organizations.employee",
                        verbose_name="Создал",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_entries",
                        to="operational_log.operationalshift",
                        verbose_name="Оперативная смена",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_operational_drafts",
                        to="organizations.employee",
                        verbose_name="Последним изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "черновая запись смены",
                "verbose_name_plural": "черновые записи смены",
                "ordering": ("position", "pk"),
                "indexes": [
                    models.Index(
                        fields=["shift", "is_removed", "position"],
                        name="op_draft_shift_order_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationalDraftRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_number",
                    models.PositiveIntegerField(
                        verbose_name="Номер редакции"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создана"),
                            ("UPDATED", "Изменена"),
                            ("REORDERED", "Изменён порядок"),
                            ("REMOVED", "Убрана из черновика"),
                            ("RESTORED", "Восстановлена"),
                        ],
                        max_length=16,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict,
                        editable=False,
                        verbose_name="Снимок редакции",
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        verbose_name="SHA-256 редакции",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Время изменения",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_draft_revisions",
                        to="organizations.employee",
                        verbose_name="Изменил",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="operational_log.operationaldraftentry",
                        verbose_name="Черновая запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "редакция черновой записи",
                "verbose_name_plural": "редакции черновых записей",
                "ordering": ("entry", "revision_number"),
            },
        ),
        migrations.AddConstraint(
            model_name="operationalshift",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_end_at__gt", models.F("planned_start_at"))
                ),
                name="op_shift_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("OPEN", "HANDOVER_PREPARATION"),
                    )
                ),
                fields=("journal",),
                name="uniq_active_operational_shift",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalshiftmember",
            constraint=models.UniqueConstraint(
                fields=("shift", "employee"),
                name="uniq_operational_shift_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaldraftentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="op_draft_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaldraftentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="op_draft_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaldraftrevision",
            constraint=models.UniqueConstraint(
                fields=("entry", "revision_number"),
                name="uniq_operational_draft_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaldraftrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_number__gte", 1)),
                name="op_revision_number_positive",
            ),
        ),
    ]
